global:
  resolve_timeout: 1m
  smtp_smarthost: "mailpit:1025"
  smtp_from: "alertmanager@arch-labs.local"
  smtp_require_tls: false

route:
  receiver: "mailpit-email"
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1m

receivers:
  - name: "mailpit-email"
    email_configs:
      - to: "student@arch-labs.local"
        send_resolved: true

        ##Alertmanager отправляет email через SMTP-сервер mailpit:1025
##Mailpit принимает письмо
##Ты открываешь localhost:8025 и видишь алерт как письмо