services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: arch_app
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: archdb
      DB_USER: archuser
      DB_PASSWORD: archpass
      REDIS_HOST: keydb
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_started
      rabbitmq:
        condition: service_started

## 8025 — веб-интерфейс Mailpit
## 1025 — SMTP-порт, куда Alertmanager будет отправлять письма
  mailpit:
    image: axllent/mailpit:v1.21
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
    depends_on:
      - app



  redis_exporter:
    image: oliver006/redis_exporter:v1.67.0
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: redis://keydb:6379
    depends_on:
      - keydb


  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ../monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus
      - mailpit


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16
    container_name: arch_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: archdb
      POSTGRES_USER: archuser
      POSTGRES_PASSWORD: archpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U archuser -d archdb"]
      interval: 5s
      timeout: 5s
      retries: 10


  notification_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: notification_worker
    command: ["python", "worker.py"]
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_started


  grafana:
    image: grafana/grafana:11.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  keydb:
    image: eqalpha/keydb:x86_64_v5.3.3
    container_name: keydb
    command: "keydb-server /etc/keydb/redis.conf --server-threads 2"
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
volumes:
  rabbitmq_data:
  keydb_data:
  postgres_data:
  grafana_data: