services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: arch_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: archdb
      DB_USER: archuser
      DB_PASSWORD: archpass
      REDIS_HOST: keydb
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: arch_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: archdb
      POSTGRES_USER: archuser
      POSTGRES_PASSWORD: archpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U archuser -d archdb"]
      interval: 5s
      timeout: 5s
      retries: 10


  keydb:
    image: eqalpha/keydb:x86_64_v5.3.3
    container_name: keydb
    command: "keydb-server /etc/keydb/redis.conf --server-threads 2"
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
volumes:
  keydb_data:
  postgres_data: